---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4871/workspace/MAWebApp1-CICD/target/MAWebApp1.war"
        dest: "/opt/tomcat/webapps/MAWebApp1.war"
        remote_src: nol

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
